---

os: linux

dist: focal

language: shell

env:
  jobs:
    - MOLECULE_SCENARIO_NAME="ubuntu-20.04"
    - MOLECULE_SCENARIO_NAME="ubuntu-18.04"
    - MOLECULE_SCENARIO_NAME="centos-8"
    - MOLECULE_SCENARIO_NAME="centos-7"
    - MOLECULE_SCENARIO_NAME="suse-15"
    - MOLECULE_SCENARIO_NAME="debian-10"
    - MOLECULE_SCENARIO_NAME="fedora-32"

jobs:
  allow_failures:
    - env: MOLECULE_SCENARIO_NAME="centos-8"
    - env: MOLECULE_SCENARIO_NAME="centos-7"
    - env: MOLECULE_SCENARIO_NAME="suse-15"
    - env: MOLECULE_SCENARIO_NAME="debian-10"
    - env: MOLECULE_SCENARIO_NAME="fedora-32"

before_install:
  - |
    sudo apt-get update
    sudo apt-get -y install bridge-utils dnsmasq-base ebtables libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev qemu-kvm qemu-utils ruby-dev

  - |
    curl -Os https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_x86_64.deb
    curl -Os https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_SHA256SUMS
    curl -Os https://releases.hashicorp.com/vagrant/2.2.10/vagrant_2.2.10_SHA256SUMS.sig
    curl -skL https://keybase.io/hashicorp/pgp_keys.asc | sudo gpg --import
    gpg --verify vagrant_2.2.10_SHA256SUMS.sig vagrant_2.2.10_SHA256SUMS
    sha256sum -c vagrant_2.2.10_SHA256SUMS 2>&1 | grep OK
    sudo dpkg -i vagrant_2.2.10_x86_64.deb
    sudo vagrant plugin install vagrant-libvirt
    rm -rf vagrant_2.2.10_*

  - |
    sudo apt-get update
    sudo apt-get -y purge python3-openssl
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --ignore-installed --requirement requirements.txt

install:
  - |
    export COLLECTION=$(echo $TRAVIS_REPO_SLUG | sed 's/^.*\/ansible-collection-/\//g')
    mkdir -p $HOME/.ansible/roles
    mkdir -p $HOME/.ansible/collections/alvistack
    ln -s $TRAVIS_BUILD_DIR $HOME/.ansible/collections/alvistack/$COLLECTION

script:
  - |
    source ./scripts/run-tests.sh \
      && sudo -E molecule dependency -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule lint -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule syntax -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule converge -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule side-effect -s $MOLECULE_SCENARIO_NAME \
      && sudo -E molecule verify -s $MOLECULE_SCENARIO_NAME

after_success:
  - |
    if [[ -n "$TRAVIS_TAG" ]] && [[ "ubuntu-20.04" =~ ^$MOLECULE_SCENARIO_NAME ]]; then
      sed -i "s/VERSION/$TRAVIS_TAG/g" galaxy.yml
      sudo -E ansible-galaxy collection build
      sudo -E ansible-galaxy collection publish --api-key $ANSIBLE_GALAXY_API_KEY --no-wait *.tar.gz
    fi
