---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: alvistack.sqlite
      tags: alvistack.sqlite

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.bleachbit
      tags: alvistack.bleachbit

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.restic
      tags: alvistack.restic

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.rclone
      tags: alvistack.rclone

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.uget
      tags: alvistack.uget

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.filezilla
      tags: alvistack.filezilla

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.transmission
      tags: alvistack.transmission

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.teamviewer
      tags: alvistack.teamviewer

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.teams
      tags: alvistack.teams

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.wireguard
      tags: alvistack.wireguard

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.flatpak
      tags: alvistack.flatpak

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.gparted
      tags: alvistack.gparted

    - name: include role
      ansible.builtin.include_role:
        name: alvistack.gnucash
      tags: alvistack.gnucash
