---

# Copyright 2023 Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: 50-misc-install | all
  hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include role
      ansible.builtin.include_role:
        name: sqlite
      tags: sqlite

    - name: include role
      ansible.builtin.include_role:
        name: bleachbit
      tags: bleachbit

    - name: include role
      ansible.builtin.include_role:
        name: restic
      tags: restic

    - name: include role
      ansible.builtin.include_role:
        name: rclone
      tags: rclone

    - name: include role
      ansible.builtin.include_role:
        name: uget
      tags: uget

    - name: include role
      ansible.builtin.include_role:
        name: filezilla
      tags: filezilla

    - name: include role
      ansible.builtin.include_role:
        name: transmission
      tags: transmission

    - name: include role
      ansible.builtin.include_role:
        name: teamviewer
      tags: teamviewer

    - name: include role
      ansible.builtin.include_role:
        name: wireguard
      tags: wireguard

    - name: include role
      ansible.builtin.include_role:
        name: flatpak
      tags: flatpak

    - name: include role
      ansible.builtin.include_role:
        name: gparted
      tags: gparted

    - name: include role
      ansible.builtin.include_role:
        name: gnucash
      tags: gnucash
